name: cellpose
dependencies:
  - python<=3.7
  - pip
  - mkl=2019.3
  - numpy
  - scikit-image
  - numba>=0.43.1
  - pyqt
  - scipy
  - matplotlib
  - pip:
    - mxnet-mkl
    - opencv_python
    - pyqtgraph
    - natsort
    - google-cloud-storage
    - tqdm
    - cellpose
