name: cellpose
dependencies:
  - python==3.9.23
  - pip
  - pip:
    - --index-url https://download.pytorch.org/whl/cu128 # [win] # Only for Windows: Use non-PyPi torch wheels for CUDA support
    - --extra-index-url https://pypi.org/simple # [win] # Only for Windows: Use PyPi for everything else
    - qtpy
#    - PyQt5.sip
    - numpy>=1.20.0
    - scipy
    - torch>=1.6
    - opencv-python-headless
    - pyqtgraph>=0.11.0rc0
    - natsort
    - google-cloud-storage
    - tqdm
    - tifffile
    - fastremap
    - cellpose
    - roifile
    - pyqt5
    - dask
    - distributed
    - dask-image
    - pyyaml
    - zarr
    - dask_jobqueue
    - bokeh
    - fill-voids
    - pooch
  
